<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[testdem1 started]]>
    </line>
    <line>
      <![CDATA[testdem2 started]]>
    </line>
    <line>
      <![CDATA[testdem started]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="108" started-at="2021-03-10T11:14:45 IST" finished-at="2021-03-10T11:14:46 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="108" started-at="2021-03-10T11:14:45 IST" finished-at="2021-03-10T11:14:46 IST">
      <class name="com.citi.test.DemoTest1">
        <test-method status="FAIL" signature="testDemo1()[pri:0, instance:com.citi.test.DemoTest1@8646db9]" name="testDemo1" duration-ms="18" started-at="2021-03-10T11:14:45 IST" finished-at="2021-03-10T11:14:45 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.citi.test.DemoTest1.testDemo1(DemoTest1.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testdem1 started]]>
            </line>
          </reporter-output>
        </test-method> <!-- testDemo1 -->
        <test-method status="PASS" signature="testDemo2()[pri:0, instance:com.citi.test.DemoTest1@8646db9]" name="testDemo2" duration-ms="4" started-at="2021-03-10T11:14:46 IST" depends-on-methods="com.citi.test.DemoTest1.testDemo1" finished-at="2021-03-10T11:14:46 IST">
          <reporter-output>
            <line>
              <![CDATA[testdem2 started]]>
            </line>
            <line>
              <![CDATA[testdem started]]>
            </line>
          </reporter-output>
        </test-method> <!-- testDemo2 -->
      </class> <!-- com.citi.test.DemoTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
